website/card_solver/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from website.models import User


class CardsForm(FlaskForm):
    cards = StringField('Cards (space separated)',
                        validators=[DataRequired()])
    target = IntegerField('Target',
                            validators=[DataRequired()])
    submit = SubmitField('Calculate')

website/recipes/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, IntegerField, SubmitField, TextAreaField, SelectMultipleField, widgets
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, NumberRange
from flask_login import current_user
from website.models import Recipe

class MultiCheckboxField(SelectMultipleField):
    widget = widgets.ListWidget(prefix_label=False)
    option_widget = widgets.CheckboxInput()

class RecipeForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired(),
                        Length(min=2, max=100)])
    description = StringField('Description',
                        validators=[DataRequired()])
    picture = FileField('Picture',
                        validators=[
                                    FileAllowed(['jpg', 'png'])])
    time = IntegerField('Time (minutes)',
                        validators=[DataRequired(),
                        NumberRange(0,10000)])
    people = IntegerField('People',
                        validators=[DataRequired(),
                        NumberRange(0,100)])
    difficulty = StringField('Difficulty',
                        validators=[DataRequired(),
                        Length(min=2, max=16)])
    source_name = StringField('Source',
                        validators=[Length(min=2, max=1000)])
    source_link = StringField('Link',
                        validators=[])
    ingredients = TextAreaField('Ingredients',
                        validators=[DataRequired()])
    method = TextAreaField('Method',
                        validators=[DataRequired()])
    notes = TextAreaField('Notes',
                        validators=[])
    tags = MultiCheckboxField('Tags', choices = [
        ('Vegetarian','Vegetarian'),
        ('One-pot','One-pot'),
        ('Spicy','Spicy'),
        ('Hard ingredients','Hard ingredients')])
    type = MultiCheckboxField('Type',choices = [
        ('Curry','Curry'),
        ('Pasta','Pasta'),
        ('Soup','Soup'),
        ('Meat','Meat'),
        ('Caserole','Caserole'),
        ('Main','Main'),
        ('Starter','Starter'),
        ('Dessert','Dessert'),
        ('India','Indian'),
        ('Thailand','Thai'),
        ('China','Chinese'),
        ('Breakfast','Breakfast')])
    submit = SubmitField('Submit')

class RecipeFilterForm(FlaskForm):
    min_time = StringField('Min')
    max_time = StringField('Max')
    tags = MultiCheckboxField('Tags', choices = [
        ('Vegetarian','Vegetarian'),
        ('One-pot','One-pot'),
        ('Spicy','Spicy'),
        ('Hard ingredients','Hard ingredients')])
    type = MultiCheckboxField('Type',choices = [
        ('Curry','Curry'),
        ('Pasta','Pasta'),
        ('Soup','Soup'),
        ('Meat','Meat'),
        ('Caserole','Caserole'),
        ('Main','Main'),
        ('Starter','Starter'),
        ('Dessert','Dessert'),
        ('India','Indian'),
        ('Thailand','Thai'),
        ('China','Chinese'),
        ('Breakfast','Breakfast')])
    submit = SubmitField('Submit')

website/card_solver/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from website.card_solver.forms import CardsForm
from website.card_solver.utils import solve

card_solver_blueprint = Blueprint('card_solver', __name__)

@card_solver_blueprint.route('/card_solver', methods=['GET','POST'])
def card_solver():
    form = CardsForm()
    if form.validate_on_submit():
        cards = form.cards.data.strip().split(' ')
        target = form.target.data
        answer = solve(cards, target)
        if answer[0]:
            flash(answer[1], 'success')
        else:
            flash(answer[1], 'danger')
        return redirect(url_for('card_solver.card_solver'))
    elif request.method == 'GET':
        form.target.data = 24
    return render_template('card_solver.html', title='Card Solver',
                            form=form)

website/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    return render_template('home.html')


@main.route('/about')
def about():
    return render_template('about.html', title='About')

@main.route('/excello')
def excello():
    return render_template('excello.html', title='Excello')

website/recipes/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import current_user, login_required
from website import db
from website.models import Recipe
from website.recipes.forms import RecipeForm, RecipeFilterForm
from website.recipes.utils import save_picture
import os
import flask_sqlalchemy

recipes = Blueprint('recipes', __name__)

@recipes.route("/recipe/new", methods=['GET', 'POST'])
@login_required
def new_recipe():
    form = RecipeForm()
    if form.validate_on_submit():
        picture_file = save_picture(form.picture.data)
        recipe = Recipe(title=form.title.data,
            description=form.description.data,
            time=form.time.data,
            image_file=picture_file,
            people=form.people.data,
            difficulty=form.difficulty.data,
            source_name=form.source_name.data,
            source_link=form.source_link.data,
            ingredients=form.ingredients.data,
            method=form.method.data,
            notes=form.notes.data,
            tags=",".join(form.tags.data),
            type=",".join(form.type.data))
        db.session.add(recipe)
        db.session.commit()
        flash('Your recipe has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_recipe.html', title='New Recipe',
                           form=form, legend='New Recipe')

@recipes.route("/recipe/<int:recipe_id>")
def recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template('recipe.html', title=recipe.title, recipe=recipe)

@recipes.route("/recipe/<int:recipe_id>/update", methods=['GET', 'POST'])
@login_required
def update_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    form = RecipeForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = recipe.image_file
            picture_file = save_picture(form.picture.data)
            recipe.image_file = picture_file
            os.remove(os.path.join(current_app.root_path, 'static/recipe_pics', old_pic))
        recipe.title = form.title.data
        recipe.description = form.description.data
        recipe.time = form.time.data
        recipe.people = form.people.data
        recipe.difficulty = form.difficulty.data
        recipe.source_name = form.source_name.data
        recipe.source_link = form.source_link.data
        recipe.ingredients = form.ingredients.data
        recipe.method = form.method.data
        recipe.notes = form.notes.data
        recipe.tags = ",".join(form.tags.data)
        recipe.type = ",".join(form.type.data)
        db.session.commit()
        flash('Your recipe has been updated!', 'success')
        return redirect(url_for('recipes.recipe', recipe_id=recipe.id))
    elif request.method == 'GET':
        form.title.data = recipe.title
        form.description.data = recipe.description
        form.time.data = recipe.time
        form.people.data = recipe.people
        form.difficulty.data = recipe.difficulty
        form.source_name.data = recipe.source_name
        form.source_link.data = recipe.source_link
        form.ingredients.data = recipe.ingredients
        form.method.data = recipe.method
        form.notes.data = recipe.notes
        form.tags.data = recipe.tags.split(",")
        form.type.data = recipe.type.split(",")
    return render_template('create_recipe.html', title='Update Recipe',
                           form=form, legend='Update Recipe')


@recipes.route("/recipes", methods=["POST","GET"])
def all():
    form = RecipeFilterForm()
    if form.validate_on_submit():
        return redirect(url_for('recipes.all',
                            max=form.max_time.data,
                            min=form.min_time.data,
                            tags=form.tags.data,
                            type=form.type.data))
    else:
        # Process arguemnts
        page = request.args.get('page', 1, type=int)
        max = request.args.get('max', default=10000, type=int)
        min = request.args.get('min', default=0, type=int)
        type = request.args.getlist('type')
        tags = request.args.getlist('tags')
        # Refill form
        if max != 10000:
            form.max_time.data = max
        if min != 0:
            form.min_time.data = min
        form.tags.data = tags
        form.type.data = type
        # Do filtering
        recs = Recipe.query.filter(Recipe.time<max)\
                            .filter(Recipe.time>min)\
        # all didnt work for some reason so used de morgans
        type_ids = [r.id for r in recs if not any([not t in r.type.split(",") for t in type])]
        tags_ids = [r.id for r in recs if not any([not t in r.tags.split(",") for t in tags])]
        recs = recs.filter(Recipe.id.in_(type_ids))\
                            .filter(Recipe.id.in_(tags_ids))\
                            .order_by(Recipe.id.desc())\
                            .paginate(page=page, per_page=10)
    return render_template('recipes.html', recipes=recs, form=form, legend="Filter")

website/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from website import db, bcrypt
from website.models import User
from website.users.forms import (LoginForm, UpdateAccountForm, RegistrationForm, ResetPasswordForm)
from website.users.utils import save_picture, send_request_email, send_set_email
import os

users = Blueprint('users', __name__)


@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            if next_page:
                return redirect(next_page)
            else:
                return redirect(url_for('main.home'))
        else:
            flash('Log In Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash("Secret_Password").decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        send_request_email(user)
        db.session.add(user)
        db.session.commit()
        flash('Access has been requested', 'success')
        return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route("/add_user/<token>", methods=['GET', 'POST'])
def add_user(token):
    user = User.verify_request_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.register'))
    send_set_email(user)
    flash('Password set email sent to user', 'success')
    return redirect(url_for('main.home'))

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = current_user.image_file
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            if old_pic != 'default.jpg':
                os.remove(os.path.join(current_app.root_path, 'static/profile_pics', old_pic))
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static',
                        filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                            image_file=image_file, form=form)

website/templates/account.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
        <h2 class="account-heading">{{ current_user.username }}</h2>
        <p class="text-secondary">{{ current_user.email }}</p>
      </div>
    </div>
    <!-- Form -->
        <form action="" method="POST" enctype="multipart/form-data">
          {{ form.hidden_tag() }} <!-- CRF token -->
          <fieldset class='form-group'>
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
              {{ form.username.label(class="form-control-label") }}

              {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feed">
                  {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.username(class="form-control form-control-lg") }}
              {% endif %}
            </div>

            <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>

          </fieldset>
          <div class="formgroup">
            {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
  </div>
{% endblock content %}

website/templates/card_solver.html
{% extends "layout.html" %}

{% block content %}

    <!-- Form -->
        <form action="" method="POST" enctype="multipart/form-data">
          {{ form.hidden_tag() }} <!-- CRF token -->
          <fieldset class='form-group'>
            <legend class="border-bottom mb-4">Cards Solver</legend>

            {% for card in ['A','2','3','4','5','6','7','8','9','10','J','Q','K'] %}
              <button type="button" class="btn btn-primary btn-lg mb-1" onclick="addCard('{{card}}')">{{card}}</button>
            {% endfor %}
            <button type="button" class="btn btn-danger btn-lg mb-1" onclick="clearCards()">Clear</button>

            <div class="form-group">
              {{ form.cards.label(class="form-control-label") }}
              {% if form.cards.errors %}
                {{ form.cards(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feed">
                  {% for error in form.cards.errors %}
                    <span>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.cards(class="form-control form-control-lg", id="cards") }}
              {% endif %}
            </div>

            <div class="form-group">
                    {{ form.target.label(class="form-control-label") }}
                    {% if form.target.errors %}
                        {{ form.target(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.target.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.target(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


          </fieldset>
          <div class="formgroup">
            {{ form.submit(class="btn btn-outline-info btn-lg") }}
          </div>
        </form>

        {% if solution %}
          {{ solution}}
        {% endif %}

  </div>
  <script type="text/javascript">
  function addCard(card) {
      var text = document.getElementById('cards');
      if (text.value.length == 0) {
        text.value += card;
      }
      else {
        text.value += (' '+card);
      }
  }

  function clearCards() {
      var text = document.getElementById('cards');
      text.value="";
  }
  </script>

{% endblock content %}

website/templates/filter.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
  <form action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-2">{{ legend }}</legend>
      <label class="form-control-label">Time</label><br>
      <div class="row">
        <div class="col-2">
          min:
        </div>
        <div class="col-4">
          <div class="form-group">
            {{ form.min_time(class="form-control form-control-sm")}}
          </div>
        </div>
        <div class="col-2">
            max:
        </div>
        <div class="col-4">
          <div class="form-group">
            {{ form.max_time(class="form-control form-control-sm")}}
          </div>
        </div>
      </div>
      <div class="form-group">
          {{ form.tags.label(class="form-control-label") }}
          {{ form.tags(style="list-style-type:none", class="pl-0 ml-0")}}
      </div>
      <div class="form-group">
          {{ form.type.label(class="form-control-label") }}
          {{ form.type(style="list-style-type:none", class="pl-0 ml-0")}}
      </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
  </form>
</div>
{% endblock content %}

website/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <p>Hi there</p>
    <p>Welcome to my website. There's not much to see here at the minute. I'll
      be using this site to host and run my programming project, and potentially
       upload some info and things to look at.</p>
    <p>But seeing as you've come here for something, for now feel free to enjoy a video of
      me coding music live <a href="https://www.youtube.com/watch?v=ICgdRuF7ycY&t=9s">here</a></p>
{% endblock content %}

website/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Henry - {{ title }}</title>
    {% else %}
        <title>Henry</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('main.home')}}">Henry Mattinson</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- <a class="nav-item nav-link" href="{{ url_for('main.excello')}}">Excello</a> -->
              <a class="nav-item nav-link" href="{{ url_for('recipes.all')}}">Recipes</a>
              <a class="nav-item nav-link" href="{{ url_for('card_solver.card_solver')}}">24</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle"
                          src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}"
                          height="21">
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ url_for('users.account')}}">Account</a>
                    <!-- <div class="dropdown-divider"></div> -->
                    <a class="dropdown-item" href="{{ url_for('users.logout')}}">Logout</a>
                  </div>
                </li>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register')}}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
          {% with messages = get_flashed_messages(with_categories=[true], category_filter=['success','info','danger','warning']) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

          {% block content %}
          {% endblock %}
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

website/templates/recipe.html
{% extends "layout.html" %}

{% block content %}
<div class="content-section">
  <div id="summary" class="media">
      <img class="rounded mr-2"
            src={{url_for('static',filename='recipe_pics/' + recipe.image_file)}}
            height=255>
      <div class="media-body">
        <h2 class="display-4">{{recipe.title}}</h2>
        <p>{{recipe.description}}</p>
        <div id="icons" class="mt-2">
            <img src="/static/icons/people.svg" alt="" width="32" height="32" title="Bootstrap">
            <span class="mr-3">{{recipe.people}}</span>
            <img src="/static/icons/clock.svg" alt="" width="32" height="32" title="Bootstrap">
            <span class="mr-3">{{recipe.time}}</span>
            <img src="/static/icons/lock.svg" alt="" width="32" height="32" title="Bootstrap">
            <span>{{recipe.difficulty}}</span>
        </div>
        <div id="tags" class="mt-2">
          {% for tag in recipe.tags.split(",")%}
            {% if tag=="Vegetarian" or tag=="Vegan" %}
              <span class="badge badge-success">{{tag}}</span>
            {% elif tag=="Spicy" %}
              <span class="badge badge-danger">{{tag}}</span>
            {% elif tag=="Hard Ingredients" %}
              <span class="badge badge-warning">{{tag}}</span>
            {% else %}
              <span class="badge badge-primary">{{tag}}</span>
            {% endif %}
          {% endfor %}
        </div>
        <div id="author" class="mt-2">
          <img src="/static/icons/pen.svg" alt="" width="32" height="32" title="Bootstrap">
          <span><a href="{{recipe.source_link}}">{{recipe.source_name}}</a></span>
        </div>

        {% if current_user.is_authenticated %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('recipes.update_recipe', recipe_id=recipe.id) }}">Update</a>
          </div>
        {% endif %}
    </div>
  </div>

    <div class="container mt-4">
      <div class="row">
        <div class="col-4 pl-0" style="border-right: 1px solid #ccc">
          <h2>Ingredients</h2>
            <ul>
            {% for ingredient in recipe.ingredients.split('\r') %}
              <li>{{ingredient}}</li>
            {% endfor %}
            </ul>
        </div>
        <div class="col-8">
          <h2>Method</h2>
          {% for step in recipe.method.split('\r') %}
            <p>{{step}}<p>
          {% endfor %}
        </div>
      </div>
      {% for note in recipe.notes.split('\r') %}
        <p>{{note}}<p>
      {% endfor %}
    </div>
</div>

{% endblock content %}

website/templates/recipes.html
{% extends "layout.html" %}
{% block content %}
  <div class="row">
    <div class="col-3 pl-0">
      <a href="{{ url_for('recipes.new_recipe')}}" class="btn btn-outline-success btn-block mb-2">Add Recipe</a>
      <div class="content-section">
        <form action="" method="POST" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-2">{{ legend }}</legend>
            <label class="form-control-label">Time</label><br>
            <div class="row">
              <div class="col-2">
                min:
              </div>
              <div class="col-4">
                <div class="form-group">
                  {{ form.min_time(class="form-control form-control-sm")}}
                </div>
              </div>
              <div class="col-2">
                  max:
              </div>
              <div class="col-4">
                <div class="form-group">
                  {{ form.max_time(class="form-control form-control-sm")}}
                </div>
              </div>
            </div>
            <div class="form-group">
                {{ form.tags.label(class="form-control-label") }}
                {{ form.tags(style="list-style-type:none", class="pl-0 ml-0")}}
            </div>
            <div class="form-group">
                {{ form.type.label(class="form-control-label") }}
                {{ form.type(style="list-style-type:none", class="pl-0 ml-0")}}
            </div>
          </fieldset>
          <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
          </div>
        </form>
      </div>
    </div>

    <div class="col-9 pl-0">
    {% for recipe in recipes.items %}
        <article class="media content-section">
          <div class="media-body">
            <a href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">
              <img class="rounded float-left mr-2 pl-0"
                    src="{{ url_for('static', filename='recipe_pics/' + recipe.image_file) }}"
                    height="100">
            </a>
            <h2><a class="article-title" href="{{ url_for('recipes.recipe', recipe_id=recipe.id) }}">{{ recipe.title }}</a></h2>
            <p class="article-content">{{ recipe.description }}</p>
          </div>
        </article>
      {% endfor %}

      {% for page_num in recipes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if recipes.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('recipes.all', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('recipes.all', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          ...
        {% endif %}
      {% endfor %}
    </div>
{% endblock content %}